### ISSUE TITLE
peer dependencies warning on Angular 5+

### ISSUE THREAD

**Issue by artipixel** [dbfannin/ngx-logger#39] opened 2018-01-18 15:12 UTC
Getting those warnings when performing 'npm install'

```
npm WARN ngx-logger@1.1.2 requires a peer of @angular/core@^4.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-logger@1.1.2 requires a peer of @angular/common@^4.3.0 but none is installed. You must install peer dependencies yourself.

```

in package.json: 
`    "@angular/common": "5.2.1",
    "@angular/core": "5.2.1",`

**Comment by davidkarlsen** [comment] 2018-01-30 22:11
Duplicate of #33

**Comment by dbfannin** [comment] 2018-01-31 14:06
@davidkarlsen, this has been merged and released in version 2.0.0

**Closed by dbfannin** 2018-01-31 14:06 UTC
