### ISSUE TITLE
Source filename and line remains on first log entry

### ISSUE THREAD

**Issue by myonara** [dbfannin/ngx-logger#154] opened 2019-11-04 04:33 UTC
My projects starts with the following configuration:
```
LoggerModule.forRoot({
      level: NgxLoggerLevel.TRACE, 
      serverLogLevel: NgxLoggerLevel.TRACE,
      enableSourceMaps: true}),

```
I've established also the NGXLoggerMonitor to forward the messages through a socket.io connection.

```
2019-11-04T03:59:29.810Z TRACE [./src/app/shared/server-config.service.ts:159] Browser and DeviceInfo:  Object Object
2019-11-04T03:59:29.820Z TRACE [./src/app/shared/server-config.service.ts:159] S01 socket-url/nsp: 

```
The source file and line of the first trace is ok, all subsequent traces,debugs etc. show only the file and line of the first trace.

**Comment by mcpierce** [comment] 2019-12-16 03:14
I believe I'm experiencing the same issue.

I've just added ngx-logger to my project (thank you for the project) and, when I enable source maps, I see the same source reference for all log entries, even though the actual logging output is from a different place in the code:

```
2019-12-16T03:10:37.933Z DEBUG [webpack:///./src/app/library/adaptors/library.adaptor.ts:83] library state updated: {fetchingUpdates: false, comics: Array(0), updatedIds: Array(0), lastReadDates: Array(0), comicCount: 0, …}
ngx-logger.js:878 2019-12-16T03:10:37.938Z DEBUG [webpack:///./src/app/library/adaptors/library.adaptor.ts:83] Setting default language
ngx-logger.js:878 2019-12-16T03:10:38.184Z DEBUG [webpack:///./src/app/library/adaptors/library.adaptor.ts:83] getting library updates
ngx-logger.js:878 2019-12-16T03:10:38.191Z DEBUG [webpack:///./src/app/library/adaptors/library.adaptor.ts:83] collection state updated: {type: null, fetchingEntries: false, entries: Array(0), selected: null, fetchingEntry: false, …}
ngx-logger.js:878 2019-12-16T03:10:38.192Z DEBUG [webpack:///./src/app/library/adaptors/library.adaptor.ts:83] selection state changed: {comics: Array(0)}
ngx-logger.js:878 2019-12-16T03:10:38.194Z DEBUG [webpack:///./src/app/library/adaptors/library.adaptor.ts:83] library state updated: {fetchingUpdates: true, comics: Array(0), updatedIds: Array(0), lastReadDates: Array(0), comicCount: 0, …}
ngx-logger.js:878 2019-12-16T03:10:38.195Z DEBUG [webpack:///./src/app/library/adaptors/library.adaptor.ts:83] getting comic updates: timestamp=0 timeout=60 maximumRecords=100 lastRescanCount=0
ngx-logger.js:878 
```

**Comment by dbfannin** [comment] 2019-12-16 13:37
Marking as a duplicate of #129 which also references incorrect source file name and line number values.

**Closed by dbfannin** 2019-12-16 13:37 UTC
Labels: duplicate

**Comment by vinimaz** [comment] 2020-01-28 09:27
It doesn't seem to be a duplicated from #129 
I am also having the same problem

The first log works:

`2020-01-28T09:11:42.314Z INFO [./src/app/app.component.ts:60] Language changed to en`

But then all the following ones show the same line and file

`2020-01-28T09:11:46.752Z DEBUG [./src/app/app.component.ts:60] queryParams event triggered`

The console.log from the browser works correctly.

Is there any solution for it? 
If I use `ng serve --evalSourceMap=true` it works normally, but then the code cannot be debugged and the function is already deprecated.

**Comment by mcpierce** [comment] 2020-01-28 12:51
Yeah, this is most definitely not a duplicate of #129. They're completely separate pathologies. Please reconsider closing this issue as it's not a duplicate.

**Comment by vinimaz** [comment] 2020-01-28 13:01
I've opened the #166, and I think I've found where the problem is, but I'm not sure if my recommendation of change is the best one.
