### ISSUE TITLE
Angular 8 File name/line-numbers

### ISSUE THREAD

**Issue by Danny4927** [dbfannin/ngx-logger#135] opened 2019-07-26 08:21 UTC
Hi i have a problem using Angular 8 and ngx-logger: Typescript classes and line numbers are not shown like in: #69 .
My setup:
Angular: "8.1.2"
ngx-logger: "4.0.3"

I activated  "enableSourceMaps: true" in logger config and             
`"sourceMap": {
              "scripts": true
  }`
in angular.json.

Logging looks like:

`2019-07-26T07:55:25.943Z DEBUG [__tryOrUnsub@http:NaN] Logmessage`
or
`2019-07-26T07:55:13.371Z DEBUG [unknown:0] Logmessage`

Do you have any ideas why it is not working?

**Comment by Danny4927** [comment] 2019-07-26 11:40
Oh i found out it is only a problem in Firefox....in Chrome it is working. Maybe its a FF bug then...

**Comment by haakomol** [comment] 2019-09-27 09:05
I also have this problem. In Chrome I get
`2019-09-27T08:54:43.561Z DEBUG [./src/app/stacks/stacks-list/stacks-list.component.ts:35] stack-list - init`
and
`2019-09-27T08:54:49.648Z TRACE [./src/app/stacks/stacks-list/stacks-list.component.ts:55] create stack`
while in Firefox I get
`2019-09-27T08:55:10.943Z DEBUG [checkAndUpdateDirectiveInline@http:NaN] stack-list - init`
and
`2019-09-27T08:55:14.356Z TRACE [unknown:0] create stack`.

**Comment by dbfannin** [comment] 2019-12-16 13:38
Marking as a duplicate of #129 which also references incorrect source file name and line number values.

**Closed by dbfannin** 2019-12-16 13:38 UTC

**Comment by mcpierce** [comment] 2019-12-16 13:41
@dbfannin Is this really the same issue? The issue I'm seeing isn't occurring when it's minified code.

**Comment by joelthomas7777** [comment] 2020-10-30 14:32
Any idea how to get the line number and file name in Logger?

**Comment by mcpierce** [comment] 2020-10-30 16:38
> Any idea how to get the line number and file name in Logger?

For our project I abandoned this and moved to @angular-ru/logger for logging.

**Comment by joelthomas7777** [comment] 2020-10-31 07:23
Can I get the logger codes?
