### ISSUE TITLE
Exception on application start - "Uncaught TypeError: Cannot read properties of undefined (reading 'id')"

### ISSUE THREAD

**Issue by danarad05** [dbfannin/ngx-logger#272] opened 2021-11-10 11:36 UTC
Getting error when application is starting

![image](https://user-images.githubusercontent.com/71069170/141101320-a8dd3223-5df9-483e-b78b-c94043104b9c.png)

When debugging - I can see that module is ngx-logger module
![image](https://user-images.githubusercontent.com/71069170/141101560-fe4be47d-1cd4-4dcc-8413-f72d0e4a6670.png)

This is from AppModule settings:
```
LoggerModule.forRoot({
      level: environment.production ? NgxLoggerLevel.OFF : NgxLoggerLevel.DEBUG,
      serverLogLevel: NgxLoggerLevel.ERROR
    }),
```

Details:
Windows 10
Chrome  95.0.4638.69
Angular 8.3.4
ngx-logger version 3.3.12 (also tried with 4 and 5.03 versions and problem is reproduced)

**Comment by bmtheo** [comment] 2021-11-10 12:44
Any chance you provide a repro ?

If you know, do you have the same issue with another version of angular ?

**Comment by bmtheo** [comment] 2022-03-06 21:04
Closing this issue because I could not reproduce and user does not give more information

Feel free to comment on this issue if you have the problem, and hopefully you can give more infos

**Closed by bmtheo** 2022-03-06 21:04 UTC
Labels: need more info
