### ISSUE TITLE
Can't access to NGXLogger in app.init.ts, got undefined

### ISSUE THREAD

**Issue by joaopalma5** [dbfannin/ngx-logger#261] opened 2021-07-21 16:17 UTC
Hello,
Can't access to NGXLogger in app.init.ts, got undefined. In below, I show relevant part of the code:

app.module.ts
```
(...)
providers: [
[
      {
        provide: APP_INITIALIZER,
        useFactory: InitializerKeycloak,
        multi: true,
        deps: [KeycloakService, NGXLogger],
      },
    ],
]
```
app.init.ts
```export function InitializerKeycloak(keycloakService: KeycloakService,
  router: Router , logger: NGXLogger): () => Promise<any> {
    console.log(logger) // undefined ```

It's my mistake? Can you help me, pls?

**Comment by bmtheo** [comment] 2021-07-22 12:37
I'm not aware of such file "app.init.ts", any chance you give us a repro so I can understand what is going on ?
You can use this tool to share the reproduction code https://stackblitz.com/

**Comment by bmtheo** [comment] 2022-03-06 21:05
Closing this issue becauseuser does not give more information

Feel free to comment on this issue if you have the problem, and hopefully you can give more infos

**Closed by bmtheo** 2022-03-06 21:05 UTC
Labels: need more info
