### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by hypery2k** [dbfannin/ngx-logger#198] opened 2020-05-05 04:06 UTC
Running into issues with circular JSON structures:
```
VM1678:1 Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'element' -> object with constructor 'Object'
    |     property 'componentProvider' -> object with constructor 'Object'
    --- property 'parent' closes the circle
    at JSON.stringify (<anonymous>)
    at eval (eval at <anonymous> (ngx-logger.js:278), <anonymous>:1:6)
    at ngx-logger.js:278
    at Array.map (<anonymous>)
    at Function.push.../../node_modules/ngx-logger/fesm5/ngx-logger.js.NGXLoggerUtils.prepareAdditionalParameters (ngx-logger.js:269)
    at NGXLogger.push.../../node_modules/ngx-logger/fesm5/ngx-logger.js.NGXLogger._log (ngx-logger.js:905)
    at NGXLogger.push.../../node_modules/ngx-logger/fesm5/ngx-logger.js.NGXLogger.error (ngx-logger.js:707)
    at LogService.push.../../libs/logger/src/lib/services/log.service.ts.LogService.error (log.service.ts:58)
    at GlobalErrorHandler.push.../../libs/errors/src/lib/global-error-handler.ts.GlobalErrorHandler.handleError (global-error-handler.ts:17)
    at dispatchEvent (core.js:19862)

```

**Comment by bmtheo** [comment] 2021-02-13 15:58
I am closing this as duplicate of #177 

This will be fixed by #223

**Closed by bmtheo** 2021-02-13 15:58 UTC
Labels: enhancement
