### ISSUE TITLE
How to update default config in production environment at run time

### ISSUE THREAD

**Issue by ctaleck** [dbfannin/ngx-logger#109] opened 2019-03-07 00:21 UTC
Related issue #7 answers how to change the logging config at **compile-time** (using environment), but I wish to know how to change the global config at **run-time**.

The `logger.updateConfig(config)` method only changes them for the current instance.

I am trying to perform this update in an `APP_INITIALIZER` of the Angular bootstrap, but it grabs a new copy of the config provided in `forRoot(config).` I wondering if the service could have another way to update the default config which is always provided to the service when initialized:

```
    // each instance of the logger should have their own config engine
    this.configService = new NgxLoggerConfigEngine(loggerConfig);
```

**Comment by dbfannin** [comment] 2019-03-07 13:42
@ctaleck, I'm trying to make sure I'm understanding your use case. 

- You have multiple instances of the logger in your app
- You're need to be able to update your logger configuration in your app's APP_INITIALIZER
- You have multiple instances of the logger, and you don't want to manually update each instance with the new config

Does that sum it up?

**Comment by ctaleck** [comment] 2019-03-13 15:33
@dbfannin A bit of clarification on each point:

- I would like one main instance of the logger config in my app that I can control through a run-time settings file that each new instance inherits from
- I would like the settings for the logger to be initialized with the Angular init process (APP_INITIALIZER) and not the .forRoot(config) process
- The multiple instances of the logger are unintentional, I only want one. Or rather inherit from one set of settings that I can control from a settings file

It seems that every time I invoke the logger service, I get a new set of config settings which was provided by the forRoot(config), and then the updateConfig(config) can be used to override that. However, I want to override the forRoot(config) settings at run time so that every new instance uses the new run time settings.

To give some context on the user story for this, I would like to be able to change the logging level for each new environment for continuous deployment without re-compiling. Only the app settings file would need to change. I hope this helps.

**Comment by bradoyler** [comment] 2019-05-10 15:47
So one workaround might be to read the logLevel from localStorage and then you can update the value in the browser console at runtime. This is how the nodejs `debug` module works.

**Comment by ctaleck** [comment] 2019-05-17 18:13
How would you get the initial settings into localStorage before the Angular app initializes?

**Comment by bradoyler** [comment] 2019-05-20 23:03
@ctaleck I don't do that. I just use `localStorage.setItem()` to override the existing defaultLogLevel at runtime.

**Comment by tomanovy** [comment] 2019-11-23 20:59
I found this solution, it's working (only not on Stackblitz, don't know why it's not able to http.get those json files): [https://stackoverflow.com/questions/54668780/how-to-configure-logger-level-for-ngx-logger-in-global-config-file/#answer-55048067](https://stackoverflow.com/questions/54668780/how-to-configure-logger-level-for-ngx-logger-in-global-config-file/#answer-55048067)
but I cannot figure out how to set it up with APP_Initializer...I'm stuck in this situation: https://ngx-logger-config.stackblitz.io... Could you guys help me?

**Comment by bmtheo** [comment] 2020-01-24 15:28
@dbfannin this would also be useful in our app

The user story is a bit different : 
We need to change the logLevel at runtime (by default in PROD mode it's set to ERROR) but if we need to investigate on an issue, we'd like to modify that logLevel to DEBUG or TRACE for example.

So the updateConfig should update all "living" instances of NGXLogger AND the future instances.

Are you open to PR for this ? and if so I was thinking of doing something like this :
```
export class NGXLogger implements OnDestroy {
  private static readonly _sharedConfig: Subject<LoggerConfig> = new Subject<LoggerConfig>();
  /** Returns an observable when the sharedConfig is changed */
  public sharedConfigChanged(): Observable<LoggerConfig> {
    return NGXLogger._sharedConfig.asObservable();
  }

  /** Updates the config for all the instances of NGXLogger */
  public updateSharedConfig(config: LoggerConfig) {
    NGXLogger._sharedConfig.next(config);
  }

...

  // each instance of the logger should have their own config engine
  this.config = new NGXLoggerConfigEngine(loggerConfig, this.sharedConfigChanged());
```

**Comment by qortex** [comment] 2020-04-09 07:53
Duplicate of #184 

Closing this issue, which will be tracked in #184

**Closed by qortex** 2020-04-09 07:53 UTC
Labels: feature request
