### ISSUE TITLE
Demo app: NullInjectorError: No provider for HttpBackend

### ISSUE THREAD

**Issue by Ixtalo** [dbfannin/ngx-logger#138] opened 2019-08-06 09:37 UTC
Hello,

I am new to ngx-logger and I do not get the demo running.

When I run `npm run demo` the compile and run process work fine, but only an empty page is shown at http://localhost:4200. Completely empty.

The browser console tells:
```
ERROR NullInjectorError: "StaticInjectorError(AppModule)[NGXLoggerHttpService -> HttpBackend]: 
  StaticInjectorError(Platform: core)[NGXLoggerHttpService -> HttpBackend]: 
    NullInjectorError: No provider for HttpBackend!"
```

What do I miss?

**Comment by viveksacademia4git** [comment] 2019-08-09 18:18
Even I am getting the same [error](https://github.com/dbfannin/ngx-logger/issues/138#issue-477274795) after following the steps mentioned on the [Demo](https://github.com/dbfannin/ngx-logger#demo-app)  
  
![image](https://user-images.githubusercontent.com/45398326/62800073-bc894a00-bae2-11e9-8e37-4fb3e731b21d.png)

**Comment by mike-kolback** [comment] 2019-08-13 14:43
I too am getting the same error.  Followed the demo steps to a tee.

**Comment by robwatt** [comment] 2019-08-14 22:08
I imported HttpClientModule as described in (https://github.com/dbfannin/ngx-logger/issues/137), and the error went away.

**Comment by francves** [comment] 2019-08-16 15:17
Thanks @robwatt I add de HttpClientModule and its works!

**Comment by viveksacademia4git** [comment] 2019-09-16 18:03
@robwatt I think the cause of the issue was something else because the project in which I was trying to implement the logging functionality was already importing the ***HttpClientModule*** in the ***application.module.ts***. Anyways, what matters is that the issue has been addressed successfully. @Ixtalo Can you please close the issue now.

**Comment by viveksacademia4git** [comment] 2019-09-16 18:06
@Ixtalo Can you please close the issue now.

**Comment by Ixtalo** [comment] 2019-09-21 06:34
Thanks!
Indeed, as @robwatt said and as described in #137, adding `HttpClientModule`imports to `projects/demo/src/app/app.module.ts` solves the issue.
The issue can be closed when fix is included in master branch.

**Comment by dbfannin** [comment] 2019-10-23 11:37
thanks to @martin-reiterer's update, this should now be resolved in ngx-logger@4.0.7

**Closed by dbfannin** 2019-10-23 11:37 UTC

**Comment by markterrill** [comment] 2020-09-17 03:19
Hi, sorry to kick the dead horse, but surely this shouldn't be triggering an error when you aren't running the demo?

Just including the module per docs I'm getting this error. We shouldn't need to include the httpclientmodule if we aren't actually using server loging.

**Comment by eivanphils** [comment] 2022-01-11 13:42
Hi, I had the same problem, but I can solve it. I install this version "ngx-logger": "^4.3.3"

It's necessary to add HttpClientModule into app module. Like this:


![image](https://user-images.githubusercontent.com/1909869/148953364-c04e47ca-fdb6-4696-a7ef-96a7e5869e4d.png)
