### ISSUE TITLE
How to add auth token to the custum header ?

### ISSUE THREAD

**Issue by chandrakanth25** [dbfannin/ngx-logger#222] opened 2021-02-11 18:45 UTC
Could some one please provide an example where to add auth token to the custom header.
If I pass auth token to the below line of code, its throwing error. please suggest.
this.logger.setCustomHttpHeaders(new HttpHeaders({'X-Custom-Header': '123456'}));

**Comment by bmtheo** [comment] 2021-02-12 09:34
Closing as duplicate of #221

**Closed by bmtheo** 2021-02-12 09:34 UTC
