### ISSUE TITLE
passing the path into the log file and browser console

### ISSUE THREAD

**Issue by frankthepunk** [dbfannin/ngx-logger#57] opened 2018-04-12 06:36 UTC
Hi,
my name is Frank,
I got a concern.
Is it possible to log automatically the file name or even better the path of the calling file?
I use your very comfortable NGXLogger inside an Angular-application and the logs are written inside the C# backend.
Of course I could write inside my node.js
this.logger.debug('mySpecial.component.ts | the message');
, but it would be great, when that is integrated in NGXLogger.
Sincerely,
Frank

**Comment by dbfannin** [comment] 2018-04-12 13:53
@frankthepunk, funny you should mention this. We just merged in #56 and published ngx-logger@2.2.0. this will now log caller file name and line number.

**Comment by danibs** [comment] 2018-04-19 06:38
Hi,
I updated to last version but only console.log shows the real name and position of log

```
console.log('HELLO console.log');
this.logger.debug('HELLO this.logger.debug');
```

![immagine](https://user-images.githubusercontent.com/30932554/38975129-05e490aa-43ad-11e8-9a26-3f282a593e26.png)

**Comment by dbfannin** [comment] 2018-04-19 16:02
@danibs, the file/path name is in the metastring prefix of the logged message. in your case ```[router.js:4093]```.

**Comment by danibs** [comment] 2018-04-20 10:59
What I mean is that console.log tell me what is the source of filename:lineNumber and this information is more usefull during development.  The two lines:
```
console.log('HELLO console.log');
this.logger.debug('HELLO this.logger.debug');
```
are in the same file, the first above the second.
Maybe having both informations will be the best.

**Comment by dbfannin** [comment] 2018-04-20 21:07
@danibs, it's still not clear to me what the problem is. 

Is it that the right hand side file name and line number is different? if so, that is known, and there isn't a solution for that yet. 

Is it that the file name and number in the metastring is incorrect? If so, we can look into why this isn't working as expected.

**Comment by danibs** [comment] 2018-04-21 13:14
@dbfannin, what you said <<if so, that is known, and there isn't a solution for that yet>> is the answer of my doubts. I thought that with new version you found a solution for that!

I didn't check if file name and number in the metastring is incorrect, sorry. 
Thanks!

**Comment by danibs** [comment] 2018-04-21 13:25
I thought to one thing: maybe that Node, during compile, translate `console.log` adding file informations?
My fault that I didn't look inside "compiled" files...

**Comment by danibs** [comment] 2018-04-22 16:50
@dbfannin, I check inside transpilled file and `console.log` is not changed or translated to something else.

I found this: https://stackoverflow.com/a/49283274 
Could it help you?

Thanks!

**Comment by dbfannin** [comment] 2018-09-27 13:29
closing as a duplicate of #69

**Closed by dbfannin** 2018-09-27 13:29 UTC

**Comment by dungtran98** [comment] 2021-08-05 09:33
![image](https://user-images.githubusercontent.com/51997678/128327898-5c5988f1-0518-4f69-b2ce-2cdb1943fbb1.png)
can i change ./src/app/app.component.ts:222 -> webpack:///./src/app/app.component.ts:222

**Comment by bmtheo** [comment] 2021-08-05 19:32
I think for now it's not possible, it's coming with V5 :)
